import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';
import { Session } from '../../sessions/entities/session.entity';

/**
 * LessonPlan Document Type
 * Represents a MongoDB document for a lesson plan generated by AI
 */
export type LessonPlanDocument = HydratedDocument<LessonPlan>;

/**
 * Lesson Plan Schema
 * 
 * This schema stores AI-generated lesson plans for sessions.
 * Each session can have one lesson plan that includes:
 * - Structured lesson outline
 * - Progress checklist
 * - Recommended resources
 * - Homework assignments
 * 
 * The plan is generated when a booking is accepted or manually requested by the teacher.
 */
@Schema({ timestamps: true })
export class LessonPlan {
  /**
   * Reference to the Session this lesson plan belongs to
   * One-to-one relationship: one session = one lesson plan
   */
  @Prop({ type: Types.ObjectId, ref: Session.name, required: true, unique: true })
  sessionId: Types.ObjectId;

  /**
   * The skill being taught in this session
   * Example: "Guitare", "Anglais", "Photoshop"
   */
  @Prop({ required: true })
  skill: string;

  /**
   * Student's level: "beginner", "intermediate", or "advanced"
   * Used by AI to tailor the lesson plan complexity
   */
  @Prop({ required: true, enum: ['beginner', 'intermediate', 'advanced'] })
  level: string;

  /**
   * Session duration in minutes
   * Used by AI to structure the lesson timing
   */
  @Prop({ required: true })
  duration: number;

  /**
   * Learning goal for this session
   * Example: "learn basic chords", "practice French conversation"
   * Used by AI to focus the lesson content
   */
  @Prop({ required: true })
  goal: string;

  /**
   * Structured lesson plan outline
   * Contains sections like:
   * - Warm-up
   * - Main learning blocks
   * - Practice exercises
   * - Summary
   * 
   * Stored as a formatted string (can be markdown or plain text)
   */
  @Prop({ required: true, type: String })
  plan: string;

  /**
   * Progress checklist items
   * Array of learning objectives that can be checked off
   * Example: ["Understand basic chords", "Play progression C-Am-F-G"]
   */
  @Prop({ type: [String], default: [] })
  checklist: string[];

  /**
   * Recommended resources
   * Array of URLs or resource descriptions
   * Example: ["https://youtube.com/...", "PDF guide link"]
   */
  @Prop({ type: [String], default: [] })
  resources: string[];

  /**
   * Homework assignment after the session
   * Contains exercises, recap, and next steps
   */
  @Prop({ type: String, default: '' })
  homework: string;

  /**
   * Progress tracking: which checklist items are completed
   * Maps checklist index to completion status
   * Example: { "0": true, "1": false, "2": true }
   */
  @Prop({ type: Map, of: Boolean, default: {} })
  progress: Map<string, boolean>;

  /**
   * Timestamp when the plan was generated
   * Automatically set by Mongoose timestamps
   */
  createdAt?: Date;

  /**
   * Timestamp when the plan was last updated
   * Automatically set by Mongoose timestamps
   */
  updatedAt?: Date;
}

/**
 * Create the Mongoose schema from the LessonPlan class
 */
export const LessonPlanSchema = SchemaFactory.createForClass(LessonPlan);

